site_name: mac-setup
use_directory_urls: false
nav:
  - Home: index.md
  - dotfiles: dotfiles.md
  - Applicazioni: applications/index.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
    - rust
