site_name: mac-setup
use_directory_urls: false
repo_url: https://github.com/magobaol/mac-setup
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
    - yaml
markdown_extensions:
  - admonition    
nav:
  - Home: index.md
  - About: about.md
  - Argomenti:
    - topics/mac-installation.md
    - topics/dotfiles.md
    - topics/mac-automation.md
    - topics/macos-defaults.md
    - topics/dev-config.md
  - Applicazioni:
    - applications/index.md
    - applications/1password.md
    - applications/bash.md
    - applications/bash-it.md
    - applications/dotbot.md
    - applications/dropbox.md
    - applications/exactscan.md
    - applications/git.md
    - applications/goodsync.md    
    - applications/google-drive.md
    - applications/homebrew.md
    - applications/inputrc.md
    - applications/iterm2.md
    - applications/launchbar.md
    - applications/mackup.md
    - applications/mkdocs.md    
    - applications/oh-my-zsh.md
    - applications/spotify-cli.md
    - applications/ssh.md
    - applications/zsh.md    