site_name: mac-setup
use_directory_urls: false
repo_url: https://github.com/magobaol/mac-setup
nav:
  - Home: index.md
  - dotfiles: topics/dotfiles.md
  - Applicazioni: applications/index.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
    - rust
